/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminApprovalTypesRouteImport } from './routes/admin.approval-types'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AppApplicationsRouteImport } from './routes/app.applications'
import { Route as AppChecklistRouteImport } from './routes/app.checklist'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AuthorityAnalyticsRouteImport } from './routes/authority.analytics'
import { Route as AuthorityInboxRouteImport } from './routes/authority.inbox'
import { Route as AppApplicationsIndexRouteImport } from './routes/app.applications.index'
import { Route as AppApplicationsIdRouteImport } from './routes/app.applications.$id'
import { Route as AppApplicationsNewRouteImport } from './routes/app.applications.new'
import { Route as AuthorityApplicationsIdRouteImport } from './routes/authority.applications.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalTypesRoute = AdminApprovalTypesRouteImport.update({
  id: '/admin/approval-types',
  path: '/admin/approval-types',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/app/applications',
  path: '/app/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChecklistRoute = AppChecklistRouteImport.update({
  id: '/app/checklist',
  path: '/app/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/app/notifications',
  path: '/app/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityAnalyticsRoute = AuthorityAnalyticsRouteImport.update({
  id: '/authority/analytics',
  path: '/authority/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityInboxRoute = AuthorityInboxRouteImport.update({
  id: '/authority/inbox',
  path: '/authority/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AppApplicationsIndexRoute = AppApplicationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppApplicationsRoute,
} as any)
const AppApplicationsIdRoute = AppApplicationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppApplicationsRoute,
} as any)
const AppApplicationsNewRoute = AppApplicationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppApplicationsRoute,
} as any)
const AuthorityApplicationsIdRoute = AuthorityApplicationsIdRouteImport.update({
  id: '/authority/applications/$id',
  path: '/authority/applications/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/approval-types': typeof AdminApprovalTypesRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/applications': typeof AppApplicationsRouteWithChildren
  '/app/checklist': typeof AppChecklistRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/authority/analytics': typeof AuthorityAnalyticsRoute
  '/authority/inbox': typeof AuthorityInboxRoute
  '/app/applications/$id': typeof AppApplicationsIdRoute
  '/app/applications/new': typeof AppApplicationsNewRoute
  '/authority/applications/$id': typeof AuthorityApplicationsIdRoute
  '/app/applications/': typeof AppApplicationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/approval-types': typeof AdminApprovalTypesRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/checklist': typeof AppChecklistRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/authority/analytics': typeof AuthorityAnalyticsRoute
  '/authority/inbox': typeof AuthorityInboxRoute
  '/app/applications/$id': typeof AppApplicationsIdRoute
  '/app/applications/new': typeof AppApplicationsNewRoute
  '/authority/applications/$id': typeof AuthorityApplicationsIdRoute
  '/app/applications': typeof AppApplicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/approval-types': typeof AdminApprovalTypesRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/applications': typeof AppApplicationsRouteWithChildren
  '/app/checklist': typeof AppChecklistRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/authority/analytics': typeof AuthorityAnalyticsRoute
  '/authority/inbox': typeof AuthorityInboxRoute
  '/app/applications/$id': typeof AppApplicationsIdRoute
  '/app/applications/new': typeof AppApplicationsNewRoute
  '/authority/applications/$id': typeof AuthorityApplicationsIdRoute
  '/app/applications/': typeof AppApplicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin/approval-types'
    | '/admin/users'
    | '/app/applications'
    | '/app/checklist'
    | '/app/notifications'
    | '/app/profile'
    | '/app/settings'
    | '/authority/analytics'
    | '/authority/inbox'
    | '/app/applications/$id'
    | '/app/applications/new'
    | '/authority/applications/$id'
    | '/app/applications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin/approval-types'
    | '/admin/users'
    | '/app/checklist'
    | '/app/notifications'
    | '/app/profile'
    | '/app/settings'
    | '/authority/analytics'
    | '/authority/inbox'
    | '/app/applications/$id'
    | '/app/applications/new'
    | '/authority/applications/$id'
    | '/app/applications'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin/approval-types'
    | '/admin/users'
    | '/app/applications'
    | '/app/checklist'
    | '/app/notifications'
    | '/app/profile'
    | '/app/settings'
    | '/authority/analytics'
    | '/authority/inbox'
    | '/app/applications/$id'
    | '/app/applications/new'
    | '/authority/applications/$id'
    | '/app/applications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminApprovalTypesRoute: typeof AdminApprovalTypesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AppApplicationsRoute: typeof AppApplicationsRouteWithChildren
  AppChecklistRoute: typeof AppChecklistRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AuthorityAnalyticsRoute: typeof AuthorityAnalyticsRoute
  AuthorityInboxRoute: typeof AuthorityInboxRoute
  AuthorityApplicationsIdRoute: typeof AuthorityApplicationsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approval-types': {
      id: '/admin/approval-types'
      path: '/admin/approval-types'
      fullPath: '/admin/approval-types'
      preLoaderRoute: typeof AdminApprovalTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/applications': {
      id: '/app/applications'
      path: '/app/applications'
      fullPath: '/app/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/checklist': {
      id: '/app/checklist'
      path: '/app/checklist'
      fullPath: '/app/checklist'
      preLoaderRoute: typeof AppChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/app/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority/analytics': {
      id: '/authority/analytics'
      path: '/authority/analytics'
      fullPath: '/authority/analytics'
      preLoaderRoute: typeof AuthorityAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority/inbox': {
      id: '/authority/inbox'
      path: '/authority/inbox'
      fullPath: '/authority/inbox'
      preLoaderRoute: typeof AuthorityInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/applications/': {
      id: '/app/applications/'
      path: '/'
      fullPath: '/app/applications/'
      preLoaderRoute: typeof AppApplicationsIndexRouteImport
      parentRoute: typeof AppApplicationsRoute
    }
    '/app/applications/$id': {
      id: '/app/applications/$id'
      path: '/$id'
      fullPath: '/app/applications/$id'
      preLoaderRoute: typeof AppApplicationsIdRouteImport
      parentRoute: typeof AppApplicationsRoute
    }
    '/app/applications/new': {
      id: '/app/applications/new'
      path: '/new'
      fullPath: '/app/applications/new'
      preLoaderRoute: typeof AppApplicationsNewRouteImport
      parentRoute: typeof AppApplicationsRoute
    }
    '/authority/applications/$id': {
      id: '/authority/applications/$id'
      path: '/authority/applications/$id'
      fullPath: '/authority/applications/$id'
      preLoaderRoute: typeof AuthorityApplicationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppApplicationsRouteChildren {
  AppApplicationsIdRoute: typeof AppApplicationsIdRoute
  AppApplicationsNewRoute: typeof AppApplicationsNewRoute
  AppApplicationsIndexRoute: typeof AppApplicationsIndexRoute
}

const AppApplicationsRouteChildren: AppApplicationsRouteChildren = {
  AppApplicationsIdRoute: AppApplicationsIdRoute,
  AppApplicationsNewRoute: AppApplicationsNewRoute,
  AppApplicationsIndexRoute: AppApplicationsIndexRoute,
}

const AppApplicationsRouteWithChildren = AppApplicationsRoute._addFileChildren(
  AppApplicationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminApprovalTypesRoute: AdminApprovalTypesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AppApplicationsRoute: AppApplicationsRouteWithChildren,
  AppChecklistRoute: AppChecklistRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AuthorityAnalyticsRoute: AuthorityAnalyticsRoute,
  AuthorityInboxRoute: AuthorityInboxRoute,
  AuthorityApplicationsIdRoute: AuthorityApplicationsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
